triggers:
    - everyone
    - overwatch
    - йграть
    - умукнщту
    - щцукцфеср

players:
    - @tetra5
    - @Liftmeup
    - @Hwestar
    - @focusshifter
    - @Vhailor
    - @pingeee
    - @pprwlf
    - @sm00th
    - @qazyan
    - @Valion
    - @dbobylev